# ============================================
# Sistema de Gestión de Solicitudes - CITCD
# Universidad Surcolombiana
# ============================================

# Puerto del servidor
server.port=8080

# Nombre de la aplicación
spring.application.name=solicitudes-citcd
